# General 
save_raw: true
save_fig: false
plot_res: false
add_dd_based_prior: false
debug_mode: false
plot_status_DD: false

# Probabilistic model 
sample_method: 'Markov'
N: 500 # population size
vecK: [3] # number of defective items
nmc: 2
enlarge_tests_num_by_factors: [0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2] # The number of tests will be calculated based on the ML baseline multiplied by the scaling factors specified here.

# Encoder
code_type: 'near_constant' # options: 'bernoulli', 'near_constant'

# Decoder 
do_third_step: true
third_step_type: 'viterbi+MAP' # options: ['MLE', 'MAP_for_GE', 'viterbi', 'viterbi+MAP']

# Viterbi decoder 
num_of_paths_for_lva: 500
viterbi_time_steps: 1
max_iteration_for_map: 1000000
gamma_dict:
  '0.5': 12
  '0.6': 6
  '0.7': 6
  '0.8': 6
  '0.9': 6
  '1.0': 6
  '1.1': 6
  '1.2': 6

# Seed
random_seed: 123
numpy_seed: 123
